### ISSUE TITLE
Catalyst Client doesn't work anymore in Kernel, because it is not browser compatible

### ISSUE THREAD

**Issue by pablitar** [decentraland/catalyst-client#109]
This is likely due to two changes in catalyst client:
- Having added dependencies that are not compatible with the browser (See "can't resolve fs" errors below)
![image](https://user-images.githubusercontent.com/2048532/135639305-b01caec5-b42f-4db4-bfe4-a7b69be04c3c.png)

- Having set the target source to ES2020 (See ?? errors below)
![image](https://user-images.githubusercontent.com/2048532/135638869-a14e89c5-6bc9-48a9-adb5-dd69b901fabc.png)

Setting the target to ES2018 and configuring typescript or webpack somehow to ignore fs:
https://github.com/log4js-node/log4js-node/issues/781

**Comment by agusaldasoro** [comment]
Closing this issue as Kernel has removed the dependency to the Catalyst Client: https://github.com/decentraland/kernel/pull/196
